tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/dynamic/server.crt
        keyFile: /etc/traefik/dynamic/server.key
  certificates:
    - certFile: /etc/traefik/dynamic/server.crt
      keyFile: /etc/traefik/dynamic/server.key
      stores:
        - default
