tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/dynamic/temp.crt
        keyFile: /etc/traefik/dynamic/temp.key
  certificates:
    - certFile: /etc/traefik/dynamic/temp.crt
      keyFile: /etc/traefik/dynamic/temp.key
      stores:
        - default
