version: "3.5"

services:
  traefik:
    image: traefik:2.3
    container_name: traefik
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
        #Settings for LetsEncrypt.
      - "--certificatesresolvers.letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false" 
      
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
           - net1 
    restart: unless-stopped

  db:
    image: mariadb:10.4
    container_name: librenms_db
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    networks:
            - net1 
    restart: unless-stopped

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
    networks:
            - net1 
    restart: unless-stopped
  
  redis:
    image: redis:5.0-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    networks:
            - net1 
    restart: always

  smtp:
    image: juanluisbaptiste/postfix
    container_name: librenms_smtp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "SERVER_HOSTNAME=${LIBREDOMAIN}"
      - "SMTP_SERVER=${SMTP_SERVER}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    networks:
            - net1 
    restart: unless-stopped

  librenms:
    image: librenms/librenms:21.2.0
    container_name: librenms
    domainname: ${LIBREDOMAIN}
    hostname: librenms
    depends_on:
      - db
      - memcached
      - smtp
    volumes:
      - "./librenms:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librenms.entrypoints=https"
      - "traefik.http.routers.librenms.rule=Host(`${LIBREDOMAIN}`)"
      - "traefik.http.routers.librenms.tls=true"
      - "traefik.http.routers.librenms.tls.certresolver=letsencrypt"
      - "traefik.http.routers.librenms.tls.domains[0].main=${LIBREDOMAIN}"
      - "traefik.http.services.librenms.loadbalancer.server.port=8000"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    env_file:
      - "./librenms.env"
    networks:
           net1:
            ipv4_address: ${LIBREIP}
    restart: unless-stopped

  dispatcher:
    image: librenms/librenms:21.2.0
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
      - "SIDECAR_DISPATCHER=1"
    networks:
            - net1 
    restart: always
  
  syslog-ng:
    image: librenms/librenms:21.2.0
    container_name: librenms_syslog
    domainname: ${LIBREDOMAIN}
    hostname: librenms
    depends_on:
      - librenms
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
    env_file:
      - "./librenms.env"
    networks:
            - net1
    restart: unless-stopped

  phpipam-web:
    image: phpipam/phpipam-www:1.4x
    environment:
      - TZ=${TZ}
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    labels:
      - "traefik.enable=true"          
      - "traefik.http.routers.phpipam.entrypoints=https"
      - "traefik.http.routers.phpipam.rule=Host(`${IPAMDOMAIN}`)"
      - "traefik.http.routers.phpipam.tls=true"
      - "traefik.http.routers.phpipam.tls.certresolver=letsencrypt"
      - "traefik.http.routers.phpipam.tls.domains[0].main=${IPAMDOMAIN}"
      - "traefik.http.services.phpipam.loadbalancer.server.port=80"
    volumes:
      - "./phpipam-logo:/phpipam/css/images/logo"
    depends_on:
      - phpipam-mariadb
    networks:
            - net1


  phpipam-cron:
    image: phpipam/phpipam-cron:1.4x
    environment:
      - TZ=${TZ}
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb
    networks:
            - net1


  phpipam-mariadb:
    image: mariadb:10.5.9-focal
    environment:
      - MYSQL_ROOT_PASSWORD=${IPAMMYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - "./phpipam-db-data:/var/lib/mysql"
    networks:
            - net1

  oxidized:
    restart: unless-stopped
    image: oxidized/oxidized:latest
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
      - ./oxidized:/root/.config/oxidized
    #command removes pid-file if it exsist on boot. prevents fail on boot
    command: bash -c 'rm /root/.config/oxidized/pid; /sbin/my_init'
    networks:
           net1:
              ipv4_address: ${OXIDIP}

networks:
        net1:
          driver: bridge
          ipam:
            driver: default
            config:
                    - subnet: ${SUBNET}
          
           
