services:
  traefik:
    image: traefik:2.11.21
    container_name: traefik
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      #- "--certificatesresolvers.letsencrypt" 
      #- "--certificatesresolvers.letsencrypt.acme.storage=acme.json" 
      #- "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}" 
      #- "--certificatesresolvers.letsencrypt.acme.httpchallenge" 
      #- "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http" 
      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./certs/:/etc/traefik/dynamic/:ro" 
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
           - net1
    restart: unless-stopped
	
  pwpush:
    image: pglombardo/pwpush-ephemeral:latest
    hostname: pwpush
    container_name: pwpush
    environment:
      FORCE_SSL: ''
      EXPIRE_AFTER_DAYS_DEFAULT: '1'
      EXPIRE_AFTER_VIEWS_DEFAULT: '1'
      RETRIEVAL_STEP_DEFAULT: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pwpush.entrypoints=https"
      - "traefik.http.routers.pwpush.rule=Host(`${PWPUSHDOMAIN}`)"
      - "traefik.http.routers.pwpush.tls=true"
      - "traefik.http.routers.pwpush.tls.domains[0].main=${PWPUSHDOMAIN}"
      - "traefik.http.services.pwpush.loadbalancer.server.port=5100"
    networks:
      - net1
    restart: always

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - PASSWORD=Vinterkatt23
     # - CUSTOM_RESULTS=false #optional
     # - DB_TYPE=sqlite #optional
     # - DB_NAME=DB_NAME #optional
     # - DB_HOSTNAME=DB_HOSTNAME #optional
     # - DB_USERNAME=DB_USERNAME #optional
     # - DB_PASSWORD=DB_PASSWORD #optional
     # - DB_PORT=DB_PORT #optional
    volumes:
       - ./librespeed/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.entrypoints=https"
      - "traefik.http.routers.speedtest.rule=Host(`${SPEEDTESTDOMAIN}`)"
      - "traefik.http.routers.speedtest.tls=true"
      - "traefik.http.routers.speedtest.tls.domains[0].main=${SPEEDTESTDOMAIN}"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
    networks:
      - net1
    restart: unless-stopped

networks:
        net1:
          driver: bridge
          ipam:
            driver: default
            config:
                    - subnet: ${SUBNET}
